ecommerce_warehouse:
  target: dev

  outputs:
    dev:
      type: postgres
      host: postgres_p6
      user: airflow
      password: airflow
      port: 5432
      dbname: warehouse_db
      schema: public
      threads: 1